# Local settings
host: 0.0.0.0

# Site settings
title: Ikonic Games
email: egunn at ikonicgames.com
twitter_username: IkonicGames
github_username:  IkonicGames
facebook_username: IkonicGames
description: Ikonic Games @IkonicGames is a one-man game development 'studio', currently based somewhere in South America.  I like making games that everyone can play and nobody wants to put down.
one_liner: Developing HTML5 and crossplatform games like it's going out of style.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ikonicgames.com" # the base hostname & protocol for your site

permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

#gems:
#  - jekyll-minifier

